# trigger-repob-workflow.yml
name: 'Trigger Repo B GitHub workflow'
on:
  push:
    branches:
      - main
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          #github-token: ${{ secrets.GH_PAT }} # Fine-grained GitHub PAT that was saved as repository secret
          script: |
            try {
              result = await github.rest.actions.createWorkflowDispatch({
                owner: 'alokdnb',
                repo: 'test',
                workflow_id: 'blank.yml',
                ref: 'master',
            })
            console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
