# trigger-repob-workflow.yml
name: 'Trigger worklfow and wait'
on:
  pull_request:
    branches: [ main ]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: alokdnb
          repo: test
          github_token: ${{ secrets.GH_PAT }}
          github_user: github-user
          workflow_file_name: blank.yml
          ref: master
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
